<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Aite.ico</ApplicationIcon>
    <SelfContained>false</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishSingleFile>false</PublishSingleFile>
    <IncludeAllContentForSelfExtract>false</IncludeAllContentForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WPF-UI" Version="4.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aite.Config\Aite.Config.csproj" />
    <ProjectReference Include="..\Aite.Core\Aite.Core.csproj" />
    <ProjectReference Include="..\WPFLauncherApi\WPFLauncherApi.csproj" />
    <ProjectReference Include="..\Aite.IRC\Aite.IRC.csproj" />
  </ItemGroup>

</Project>
